### ISSUE TITLE
SG argument to initGRASS is no longer optional?

### ISSUE THREAD

**Issue by jsta** [rsbivand/rgrass7#2]
On my system, I am seeing that the `SG` argument is no longer optional despite what the docs say. Is it because of 79b5f3b4d05476c2ffacbb32e18f97a3987d5768?

**Comment by rsbivand** [comment]
This is *not* the rgrass7 package. This is a purely experimental rgrass7sf for looking at issues involving the use of sf instead of sp and rgdal for vector interchange. It is stranded until stars progresses further; going through raster is not sufficient. The real rgrass7 is on [R-Forge](https://r-forge.r-project.org/scm/viewvc.php/pkg/rgrass7/?root=spgrass) and is as on CRAN.
