### ISSUE TITLE
initGRASS() needs GRASS_PROJSHARE

### ISSUE THREAD

**Issue by rsbivand** [rsbivand/rgrass7#7]
Work on the Geomed workshop https://github.com/rsbivand/geomed19-workshop revealed that under PROJ 6 GRASS needs a shell environment variable to provide grid files.

**Comment by veroandreo** [comment]
AFAIU, proj6 support in GRASS GIS is WIP, right @metzm? See discussion in grass-dev: https://www.mail-archive.com/grass-dev@lists.osgeo.org/msg58503.html

**Comment by rsbivand** [comment]
My problem was that when I included a +nadgrids= in a proj4 string, g.proj crashed asking for GRASS_PROJSHARE. When I set the environment variable in the shell, the error message did not appear. I didn't check behaviour because I didn't need it then.

**Comment by metzm** [comment]
On Wed, Aug 14, 2019 at 8:21 PM Roger Bivand <notifications@github.com>
wrote:
>
> My problem was that when I included a +nadgrids= in a proj4 string,
g.proj crashed asking for GRASS_PROJSHARE. When I set the environment
variable in the shell, the error message did not appear. I didn't check
behaviour because I didn't need it then.

Proj6 support in GRASS is WIP. At least in master and G78, g.proj should
work with proj6.

Markus M
